sudo: required
services:
  - docker

before_install:
  - docker build -t sandhp7/docker-react -f Dockerfile.dev .

script:
  - docker run sandhp7/docker-react npm run test -- --coverage
## Above code is just to check the test results

deploy:
  provide: elasticbeanstalk
  region: 'us-east-1'
  name: 'docker-react'
  env: 'Docker-evn'
  bucket_name: 'elasticbeanstalk-us-west-sdkasnmdlksadlksandsa'
  bucker_path: 'docker-react'
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY""